spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: DETECT


  sleuth:
    baggage:
      remote-fields: RequestId
      correlation-fields:
        - RequestId
      tag-fields:
        - RequestId
    trace-id128: true



logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.amsidh.mvc: DEBUG
    org.hibernate: ERROR



resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 5
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialMaxWaitDuration: 10s
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      service1:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service1ExceptionPredicate
      service2:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service2ExceptionPredicate
      service3:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service3ExceptionPredicate
      service4:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service4ExceptionPredicate
      service5:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service5ExceptionPredicate

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10 #The number of calls after which the error rate is calculated. I have assigned it with a small value for test purpose.
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30s #Time in milliseconds, in which the circuit breaker is to stay in open state before moving to half-open state
        failureRateThreshold: 60 #The Threshold Percentage Above Which the Circuit Breaker will move from Closed to Open State.
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      service1:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service1ExceptionPredicate
      service2:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service2ExceptionPredicate
      service3:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service3ExceptionPredicate
      service4:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service4ExceptionPredicate
      service5:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service5ExceptionPredicate
